### ISSUE TITLE
Problem with parsing to json

### ISSUE THREAD

**Issue by shafiev** [dmgnx/lasagna#1]
I have add some debugging to catch this problem 

Error was in : {"ip": "54.208.242.36", "server": "www.xxxx.com", "uri": "/market-analysis/forecast/usdjpy-2016-'"", "learning": "1", "vers": "0.56", "total_processed": "205", "total_blocked": "97", "block": "1", "cscore0": "$SQL", "score0": "12", "cscore1": "$XSS", "score1": "16", "zone0": "URL", "id0": "1001", "var_name0": "", "zone1": "URL", "id1": "1013", "var_name1": ""} |||  , or } expected while parsing object/hash, at character offset 103 (before "", "learning": "1", ...") at ./naim_lasagna.pl line 65, <FILE> line 20526.
Error was in : {"ip": "54.208.242.36", "server": "www.xxx.com", "uri": "/market-analysis/\www.vulnweb.com/wtioil-2016-q1", "learning": "1", "vers": "0.56", "total_processed": "207", "total_blocked": "98", "block": "1", "cscore0": "$TRAVERSAL", "score0": "4", "zone0": "URL", "id0": "1205", "var_name0": ""} |||  illegal backslash escape sequence in string, at character offset 80 (before "\\www.vulnweb.com/wt...") at ./naim_lasagna.pl line 65, <FILE> line 20533.

**Comment by shafiev** [comment]
Anyway there problem exists with new version

, or } expected while parsing object/hash, at character offset 1564 (before ": "open+sans:300,400...") at /usr/share/perl5/JSON.pm line 171, <FILE> line 81.

**Comment by arcticf0x64** [comment]
JSON parsing replaced with an URI parser but there's still an issue with the line you emailed me. Looks like exceptions are chunked over multiple records (so much exceptions for a single endpoint ^^).
Opening a new issue.
